name: mobile_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.6
  dio: ^5.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.19.0
  material_design_icons_flutter: ^7.0.7296
  permission_handler: ^11.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  stripe_payment: ^1.1.4
  supabase_flutter: ^2.0.0
  url_launcher: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/icons/

  fonts:
    - family: Schyler
      fonts:
        - asset: assets/fonts/Schyler-Regular.ttf
        - asset: assets/fonts/Schyler-Italic.ttf
          style: italic
    - family: Trajan Pro
      fonts:
        - asset: assets/fonts/TrajanPro.ttf
        - asset: assets/fonts/TrajanPro_Bold.ttf
          weight: 700