name: animal_charity_app
version: 1.0.0+1
publish_to: none
description: Mobile application for animal charity with Flutter/Dart

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter:
    sdk: flutter
  provider: ^6.1.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  pubspec_dependency_sorter: ^1.0.5

flutter:
  uses-material-design: true