name: animal_charity_app
version: 1.0.0+1
publish_to: none
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"
description: Mobile application for animal charity with Flutter/Dart
dependencies:
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.6
  dio: ^5.3.2
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.19.0
  material_design_icons_flutter: ^7.0.7296
  permission_handler: ^11.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  stripe_payment: ^1.1.4
  supabase_flutter: ^2.0.0
  url_launcher: ^6.2.1
dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  pubspec_dependency_sorter: ^1.0.5
flutter:
  uses-material-design: true
