# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'

      - name: Install dependencies
        run: |
          cd mobile_app
          flutter pub get

      # Verify formatting - check if code is properly formatted
      - name: Verify formatting
        run: |
          cd mobile_app
          dart format --output=none --set-exit-if-changed . || echo "Code formatting issues found but continuing..."

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: |
          cd mobile_app
          flutter analyze --no-fatal-infos

      # Run tests for Flutter project
      - name: Run tests
        run: |
          cd mobile_app
          flutter test
