# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'

      # Change to mobile_app directory
      - name: Change to mobile_app directory
        run: cd mobile_app

      - name: Install dependencies
        run: |
          cd mobile_app
          flutter pub get

      # Verify formatting - раскомментировано для проверки форматирования кода
      - name: Verify formatting
        run: |
          cd mobile_app
          dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: |
          cd mobile_app
          flutter analyze

      # Run tests for Flutter project
      - name: Run tests
        run: |
          cd mobile_app
          flutter test

      # Build APK for Android
      - name: Build APK
        run: |
          cd mobile_app
          flutter build apk --release

      # Build web version
      - name: Build Web
        run: |
          cd mobile_app
          flutter build web --release
